// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"
const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDistanceChange();
void onAboveAlarmChange();
void onBelowAlarmChange();
void onMaxValueChange();
void onMinValueChange();

int distance;
float maxValue;
float minValue;
bool aboveAlarm;
bool belowAlarm;

void initProperties(){

  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onDistanceChange);
  ArduinoCloud.addProperty(aboveAlarm, READWRITE, ON_CHANGE, onAboveAlarmChange);
  ArduinoCloud.addProperty(belowAlarm, READWRITE, ON_CHANGE, onBelowAlarmChange); 
  ArduinoCloud.addProperty(maxValue, READWRITE, ON_CHANGE, onMaxValueChange);
  ArduinoCloud.addProperty(minValue, READWRITE, ON_CHANGE, onMinValueChange);
  
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
